### ISSUE TITLE
Could you please file a .tar.gz release?

### ISSUE THREAD

**Issue by onkelbeh** [jesserockz/python-juicenet#7]
Hi,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository).

Therefor I would need a release file in tar.gz format.
Home Assistant currently requires: `python-juicenet==0.1.5`

A release on Github would be OK,
but a Pypi tar.gz release **would be preferred**, because this could take use of Gentoo's mirror system.

Most of the other integrations do both.
Thanks
 \B.

**Comment by onkelbeh** [comment]
Same for 0.1.6, helped it with a fork in the meantime.

**Comment by jesserockz** [comment]
Done
